"""Add student_code column to students table

Revision ID: f7d3f9d0e6ec
Revises: ff2dbf99570f
Create Date: 2026-04-27 10:38:04.366424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d3f9d0e6ec'
down_revision: Union[str, Sequence[str], None] = 'ff2dbf99570f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'students', ['student_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'student_code')
    # ### end Alembic commands ###
