"""add embeddings to students

Revision ID: ff2dbf99570f
Revises: a3f42399adba
Create Date: 2026-04-26 19:16:20.378507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2dbf99570f'
down_revision: Union[str, Sequence[str], None] = 'a3f42399adba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mean_embeddings', sa.JSON(), nullable=True))
    op.add_column('students', sa.Column('stack_embeddings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'stack_embeddings')
    op.drop_column('students', 'mean_embeddings')
    # ### end Alembic commands ###
